<a href="https://colab.research.google.com/github/Tdiddydoit/Python-collab/blob/main/week8_assignment_8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

About the data:

Order Value: Represents the total value of the customer's order.

Customer Rating: Represents the rating given by the customer, typically between 1 and 5.

Shipping Time (Days): Represents the number of days taken to deliver the order.


**Note: This assignment and dataset have outliers and missing values generated on purpose to help you understand the importance of data cleaning and preprocessing in preparing data for analysis and modeling**

In [3]:
# Run this cell first and then answer the questions given in the assignment.

import numpy as np
import pandas as pd

np.random.seed(42)

# Generating sample data
data = {
    'Order Value': np.random.normal(100, 20, 30),
    'Customer Rating': np.random.normal(4, 0.5, 30),
    'Shipping Time (Days)': np.random.randint(1, 10, 30)
}

# Introducing missing values and outliers on purpose
data['Order Value'][np.random.choice(30, 8, replace=False)] = np.nan
data['Customer Rating'][np.random.choice(30, 7, replace=False)] = np.nan

data['Order Value'][np.random.choice(30, 7, replace=False)] = [300, 400, 300, 350, 400, 450, 700]
data['Customer Rating'][np.random.choice(30, 5, replace=False)] = [1, 5, 0.5, 5.5, 1]

# Convert to DataFrame
df = pd.DataFrame(data)

# Display the DataFrame

df

    Order Value  Customer Rating  Shipping Time (Days)
0    109.934283         3.699147                     2
1     97.234714         4.926139                     1
2    112.953771         3.993251                     7
3    130.460597              NaN                     7
4           NaN         1.000000                     8
5     95.317261              NaN                     5
6    400.000000         4.104432                     3
7    700.000000         3.020165                     8
8     90.610512         3.335907                     6
9    350.000000              NaN                     3
10    90.731646         4.369233                     1
11    90.685405         4.085684                     3
12   450.000000         3.942176                     5
13   400.000000         1.000000                     3
14    65.501643         5.000000                     1
15          NaN         0.500000                     5
16    79.743378         3.769681                     7
17   300.000000              NaN                     7
18    81.839518              NaN                     9
19    71.753926         3.118480                     3
20   129.312975         5.500000                     7
21    95.484474         3.807459                     1
22          NaN         3.661539                     4
23          NaN         4.305838                     4
24    89.112346         4.515500                     5
25   102.218452         4.465640                     7
26          NaN         3.580391                     7
27   107.513960         3.845394                     4
28          NaN         4.165632                     7
29   300.000000         4.487773                     3

In [13]:
# Count Nan Values
df.isna().sum()

Order Value             6
Customer Rating         5
Shipping Time (Days)    0
dtype: int64

In [17]:
# table showing percentage of missing values
df.isna().sum()/len(df)

Order Value             0.200000
Customer Rating         0.166667
Shipping Time (Days)    0.000000
dtype: float64